name: Build and Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        name: Build for ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                platform:
                    - { os: linux, arch: amd64 }
                    - { os: windows, arch: amd64 }
                    - { os: darwin, arch: amd64 }
                    - { os: darwin, arch: arm64 }

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"

            - name: Build and Package Artifact
              run: |
                  make package-${{ matrix.platform.os }}-${{ matrix.platform.arch }} VERSION=${{ github.ref_name }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: binary-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
                  path: dist/getctx_${{ github.ref_name }}_${{ matrix.platform.os }}_${{ matrix.platform.arch }}${{ matrix.platform.os == 'windows' && '.zip' || '.tar.gz' }}
                  if-no-files-found: error

    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: release-assets

            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref }}
                  generate_release_notes: true
                  files: release-assets/*/*
